# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_registrado_semestre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrado',
            old_name='semestre',
            new_name='carrera',
        ),
    ]
